#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# vi mode
set -o vi

#bash prompt
PS1='[\u \W]\$ '
set show-mode-in-prompt on
set vi-ins-mode-string "+"
set vi-cmd-mode-string ":"

# set terminal emulator
export TERM=xterm-color
LS_COLORS=$LS_COLORS:'ow=1;34:' ; export LS_COLORS

###
# aliases
#
alias ls='ls --color=auto'  #enable ls colors
alias tat='tmux attach-session -t'
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'

alias discord=webcord

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

bind '"\C-b": "~/"'
